### PR TITLE
Authentication for restart/shutdown

### PR DESCRIPTION
**Pull request by rgrinberg**
Using HTTP Basic and a simple static pass that's read from config

### CODE REVIEW

**Review by AnthonyMl — APPROVED** [review]
+1
@bdionne does this look ready to merge to you?

**Comment by bdionne** [comment]
looks good, but `mvn clean install` fails on the `Server` test

**Comment by bdionne** [comment]
some sort of script like [this](https://github.com/bdionne/protege-server/blob/master/scripts/shutdown.sh) would also be useful for testing this

**Comment by rgrinberg** [comment]
Which test in particular? I didn't get any failures.

If you'd like, I can also extend our integration test suite to cover some pellet functionality.

**Comment by bdionne** [comment]
+1

**Pull request merged**
