### PR TITLE
Fix pellet tests

### PR DESCRIPTION
**Pull request by rgrinberg**

### CODE REVIEW

**Comment by rgrinberg** [comment]
This only fixes 1 test for now, but it's a good start.

**Comment by rgrinberg** [comment]
The server tests are now passing. Still need to fix the client tests.

**Comment by rgrinberg** [comment]
@bdionne you mind testing this branch out for me with:

```
$ mvn test -pl client
```

and giving me the output. I think I'm running into some linux only issues where the jvm is preferring ipv6 over ipv4 for some reason

**Comment by rgrinberg** [comment]
I figured out why the command above (`$ mvn test -pl ...`) is failing but `$ mvn test` is passing. When you select a certain sub module in the runner, maven forgets (or maybe it it's intentional?) to run before/after initialization in parent modules that are dependencies (`server` in our case). In any case, there's nothing wrong with the tests, just maven not working as I expected it to.

**Comment by rgrinberg** [comment]
Currently there's a couple of failures in the client that I'm not sure how to fix:

* This part fails:
```
	@Test
	public void shouldGetVersionFromClient() throws Exception {
		PelletService aService = serviceProvider.get();

		Call<Integer> aVersionCall = aService.version(agencyOntId, ID);

		int aVersion = ClientTools.executeCall(aVersionCall);

		assertEquals(0, aVersion);
```

The last assert expects a 0 but we get a 1. I'm not sure what the correct version number should be here because this version endpoint isn't used anywhere else so it's hard for me to figure out the expected behavior.

2. If we silence the error above, we get the following error:

```
org.protege.editor.owl.client.api.exception.SynchronizationException: Commit failed, please update your local copy first

	at org.protege.editor.owl.client.LocalHttpClient.throwRequestExceptions(LocalHttpClient.java:713)
	at org.protege.editor.owl.client.LocalHttpClient.post(LocalHttpClient.java:563)
	at org.protege.editor.owl.client.LocalHttpClient.commit(LocalHttpClient.java:249)
	at com.complexible.pellet.client.PelletServiceTest.shouldGetVersionFromClient(PelletServiceTest.java:65)
```

This I'm still investigating but it would be helpful to get some hints as to why this can occur.

**Comment by bdionne** [comment]
Well at a glance, it looks like the test isn't starting with a clean ontology, perhaps the prior test is interfering.

See what protege-client endpoint is being called, if that's returning the wrong thing it may have changed since these were last run.

What this test does is pretty straightforward. Starting with a clean ontology the base revision will be `0`, as will `HEAD`.  After a single commit, it should move to `1`.

**Comment by rgrinberg** [comment]
@bdionne OK tests are now passing. It was a cleanup issue as you said.

**Comment by bdionne** [comment]
They get further for me now, client works, but it fails when it hits `Pellet::Tests`

**Comment by rgrinberg** [comment]
Very strange. Because those tests passed before the fix (I explicitly checked). I'll investigate what's the interaction there.

**Comment by bdionne** [comment]
This test seems unrelated to the client fails. When running it standalone I get the following:

`Tests run: 2069, Failures: 7, Errors: 0, Skipped: 79`

I think these fails might be related to the `owlapi` version. They are run with `4.1.3`, if I change it to `4.2.8-SNAPSHOT` which is what we're using in protege, I get:

`Tests run: 2069, Failures: 3, Errors: 0, Skipped: 79`

**Comment by bdionne** [comment]
These last changes look reasonable, updating the owlapi version and loading resources correctly. I'm still seeing failures:

`Tests run: 2069, Failures: 4, Errors: 0, Skipped: 79`

but since these are in the classifier itself and not related to the client/server interaction perhaps we can move forward with the new features and keep our eye on these

**Comment by rgrinberg** [comment]
The situation with those failing tests is actually more dire than I thought. They don't even fail reproducibly for me. There's a random element to these tests that isn't being captured by the assertions. What's worse, is that the failures also fail to report the entire set of differences. They exit when the first Class differs.

Do you think we should spend some time discussing these tests at least and what are they trying to accomplish?

@AnthonyMl do you mind giving this branch a test as well? To give us another data point.

**Comment by rgrinberg** [comment]
@bdionne the last commit brings into a mergeable state by getting rid of the `http://` hard coding.

**Comment by bdionne** [comment]
I'm getting fails again on:

`mvn test -pl client`

`Tests run: 7, Failures: 0, Errors: 7, Skipped: 0`

Also get them when I run the entire suite

**Comment by rgrinberg** [comment]
Hey Bob. That's expected. mvn test -pl client is an incorrect way to run
the tests (it doesn't run the necessary before/after calls)

When you run the entire suite do you still only get failures in a single
test suite? The Random classifier one

**Comment by bdionne** [comment]
no I see the same fails in the client. That's why I tried running it standalone

**Comment by rgrinberg** [comment]
@bdionne ok this should pass now

**Pull request merged**
